import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import './clash-display.css'
import ThemeProvider from '@/components/providers/ThemeProvider'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	                                   children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-ClashDisplay">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<main className="min-h-screen bg-white dark:bg-zinc-950 px-[175px] py-10 overflow-x-hidden">
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	)
}
