import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import './clash-display.css'
import ThemeProvider from '@/components/providers/ThemeProvider'
import grainUnderlay from '@/public/grain_underlay.png'
import Image from 'next/image'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	                                   children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-ClashDisplay bg-white dark:bg-zinc-95 overflow-x-hidden relative">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<main className="min-h-screen px-[175px] py-10">
						{children}
					</main>

					<div className="absolute inset-0 mix-blend-soft-light z-[-1] pointer-events-none w-screen max-h-full overflow-y-hidden">
						<Image src={grainUnderlay} alt="Grain underlay" className="w-full h-[8220px]" />
					</div>

				</ThemeProvider>
			</body>
		</html>
	)
}
